---
- name: Reinicio DHCP
  hosts: "meraki_servers"
  gather_facts: no
  become: yes
  tasks:
    - name: Detener DHCP
      cisco.meraki.meraki_mx_vlan:
        auth_key: "13fd3dafae84f09fc710032d6287a2a7fade1914"
      
    - name: Esperar 30 segundos
      pause:
        seconds: 30
    - name: Iniciar DHCP
      cisco.meraki.meraki_mx_vlan:
        auth_key: "13fd3dafae84f09fc710032d6287a2a7fade1914"

