---
- name: Reinicio DHCP
  hosts: "meraki_servers"
  gather_facts: no
  become: yes
  tasks:
    - name: Detener DHCP COLABORADORES
      cisco.meraki.networks_appliance_vlans:
        meraki_api_key: "{{meraki_api_key}}"
        networkId: "{{networkId}}"
        id: 15
        dhcpHandling: 'Do not respond to DHCP requests'
        state: "present"

    - name: Esperar 5 minutos
      pause:
        seconds: 30
    - name: Iniciar DHCP COLABORADORES
      cisco.meraki.networks_appliance_vlans:
        meraki_api_key: "{{meraki_api_key}}"
        networkId: "{{networkId}}"
        id: 15
        dhcpHandling: 'Run a DHCP server'
        state: "present"

    - name: Detener DHCP INVENTARIO
      cisco.meraki.networks_appliance_vlans:
        meraki_api_key: "{{meraki_api_key}}"
        networkId: "{{networkId}}"
        id: 11
        dhcpHandling: 'Do not respond to DHCP requests'
        state: "present"

    - name: Esperar 5 minutos
      pause:
        seconds: 30
    - name: Iniciar DHCP INVENTARIO
      cisco.meraki.networks_appliance_vlans:
        meraki_api_key: "{{meraki_api_key}}"
        networkId: "{{networkId}}"
        id: 11
        dhcpHandling: 'Run a DHCP server'
        state: "present"
